SUPER_CONFIG_PATH:          # super (father) config path

# Seed:
SEED: 29

# System Settings:
NUM_WORKERS: 6
PREFETCH_FACTOR: 6
DEVICE: cuda

# Data settings:
# 1. paths:
DATA_ROOT: ./datasets/
DATASETS: [DanceTrack]
DATASET_SPLITS: [train]
# 2. sampling:
SAMPLE_STEPS: [0, ]
SAMPLE_LENGTHS: [30, ]
SAMPLE_INTERVALS: [4, ]
LENGTH_PER_ITERATION:   # how many frames to process per iteration, the sample length should be divisible by this number

# Data augmentation settings:
# 1. image sizes:
AUG_RESIZE_SCALES: [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
AUG_MAX_SIZE: 1440
AUG_RANDOM_RESIZE: [400, 500, 600]
AUG_RANDOM_CROP_MIN: 384
AUG_RANDOM_CROP_MAX: 600
# 2. random shift:
AUG_MAX_SHIFT_RATIO: 0.06
# 3. bounding box overflow:
AUG_OVERFLOW_BBOX: False
# 4. color jitter:
AUG_BRIGHTNESS: 0.4
AUG_CONTRAST: 0.4
AUG_SATURATION: 0.4
AUG_HUE: 0.2
AUG_COLOR_JITTER_V2: False
# 5. for id biding:
AUG_NUM_GROUPS: 6
AUG_TRAJECTORY_OCCLUSION_PROB: 0.5
AUG_TRAJECTORY_SWITCH_PROB: 0.5

# Model settings:
# MOTIP:
ONLY_DETR: False
NUM_CLASSES: 1
NUM_ID_VOCABULARY: 50
DETR_FRAMEWORK: deformable_detr
FEATURE_DIM: 256
FFN_DIM_RATIO: 2
ID_DIM: 256
HEAD_DIM: 32
NUM_ID_DECODER_LAYERS: 6
ID_LOSS_WEIGHT: 1.0
REL_PE_LENGTH: 30
USE_AUX_LOSS: False
USE_SHARED_AUX_HEAD: True
USE_FOCAL_LOSS: False
# About DETR Framework:
BACKBONE: resnet50
DILATION: False
DETR_NUM_QUERIES: 300
DETR_NUM_FEATURE_LEVELS: 4
DETR_AUX_LOSS: True
DETR_WITH_BOX_REFINE: True
DETR_TWO_STAGE: False
DETR_HIDDEN_DIM: 256
DETR_MASKS: False
DETR_POSITION_EMBEDDING: sine
DETR_NUM_HEADS: 8
DETR_ENC_LAYERS: 6
DETR_DEC_LAYERS: 6
DETR_DIM_FEEDFORWARD: 1024
DETR_DROPOUT: 0.0
DETR_DEC_N_POINTS: 4
DETR_ENC_N_POINTS: 4
DETR_CLS_LOSS_COEF: 2.0
DETR_BBOX_LOSS_COEF: 5.0
DETR_GIOU_LOSS_COEF: 2.0
DETR_FOCAL_ALPHA: 0.25
DETR_SET_COST_CLASS: 2.0
DETR_SET_COST_BBOX: 5.0
DETR_SET_COST_GIOU: 2.0
DETR_CRITERION_BATCH_LEN: 10

# Training strategies:
BATCH_SIZE: 1
LR: 1.0e-4
LR_BACKBONE_NAMES: [backbone.0]
LR_BACKBONE_SCALE: 0.1
LR_LINEAR_PROJ_NAMES: [reference_points, sampling_offsets]
LR_LINEAR_PROJ_SCALE: 0.05
LR_DICTIONARY_NAMES: [word_to_embed, embed_to_word]
LR_DICTIONARY_SCALE: 1.0
LR_WARMUP_EPOCHS: 1
WEIGHT_DECAY: 0.0005
MAX_CLIP_NORM: 0.1
EPOCHS: 10
SCHEDULER_MILESTONES: [6, 9]
SCHEDULER_GAMMA: 0.1
DETR_NUM_TRAIN_FRAMES: 4
DETR_NUM_CHECKPOINT_FRAMES: 5
USE_DECODER_CHECKPOINT: False
ACCUMULATE_STEPS: 1
SEPARATE_CLIP_NORM: True
USE_ACCELERATE_CLIP_NORM: True

# Resumes and Pretrains:
DETR_PRETRAIN: ./pretrains/r50_deformable_detr_motip_dancetrack.pth
RESUME_MODEL:
RESUME_OPTIMIZER: True
RESUME_SCHEDULER: True
RESUME_STATES: True

# Inference settings:
INFERENCE_MODEL:            # the model path for inference
INFERENCE_DATASET: DanceTrack
INFERENCE_SPLIT: val
INFERENCE_MODE: evaluate    # evaluate or submit
INFERENCE_GROUP: default    # group name for inference
INFERENCE_MAX_LONGER: 1440  # max longer size for inference
INFERENCE_DTYPE: FP32
#ASSIGNMENT_PROTOCOL: hungarian
ASSIGNMENT_PROTOCOL: object-max
MISS_TOLERANCE: 30          # tolerance for missing frames
DET_THRESH: 0.3
NEWBORN_THRESH: 0.6
ID_THRESH: 0.2
AREA_THRESH: 0
INFERENCE_ONLY_DETR:

# Outputs settings:
OUTPUTS_DIR:                # outputs directory
USE_WANDB: False             # use wandb or not
EXP_OWNER: killian31
EXP_PROJECT: MOTIP
EXP_GROUP:
EXP_NAME:
GIT_VERSION:
SAVE_CHECKPOINT_PER_EPOCH: 1
MULTI_LAST_CHECKPOINTS: 0

# For previous version of MOTIP checkpoints:
USE_PREVIOUS_CHECKPOINT: False
