SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_masks_motip_dancetrack.yaml

DATASETS: [BFT]
DATASET_SPLITS: [train]
INFERENCE_DATASET: BFT
INFERENCE_SPLIT: test


DETR_PRETRAIN: ./pretrains/r50_deformable_detr_coco_bft.pth
DETR_DEFAULT_CLASS_IDX: 15    # class 15 is "bird" in COCO
DETR_MASKS: True
DETR_MASK_LOSS_COEF: 1.0
DETR_DICE_LOSS_COEF: 1.0
DETR_NUM_FEATURE_LEVELS: 4

ONLY_DETR: True

SAMPLE_LENGTHS: [5, ]
REL_PE_LENGTH: 20
MISS_TOLERANCE: 20

EPOCHS: 1
SCHEDULER_MILESTONES: [1, 1, ]
LR_WARMUP_EPOCHS: 0
SAVE_CHECKPOINT_PER_EPOCH: 1

USE_DECODER_CHECKPOINT: False